### PR TITLE
added a tutorial on healthkit and ability to access data sample

### PR DESCRIPTION
**Pull request by sohilpandya**
related to #43

### CODE REVIEW

**Comment by sohilpandya** [comment]
Thanks! I'll push the files for this and other projects on the repo.

**Comment by nelsonic** [comment]
It doesn't _hurt_ to have the _complete_ example code in the repo. 👍

**Comment by sohilpandya** [comment]
I've updated this PR to contain the Xcode project for this tutorial. I'll be creating another PR for additional files for the other tutorials.

**Comment by sohilpandya** [comment]
Additional Files added in #46

**Pull request merged**
